/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import DAO.NhanVienDAO;
import DAO.TkhoanDAO;
import Model.NhanVien;
import Model.TaoTkhoan.NhanVienSelectionListener;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XPS
 */
public class Chonnhanvien extends javax.swing.JDialog {
    DefaultTableModel tableModel;
    NhanVienDAO nvDAO = new NhanVienDAO();
    private NhanVienSelectionListener listener; // callback

    // Constructor có truyền listener
    public Chonnhanvien(java.awt.Frame parent, boolean modal, NhanVienSelectionListener listener) {
    super(parent, modal);
    initComponents();
    this.listener = listener; // Gán listener
    initTable();
    fillTable();
}
    
    public void initTable() {
        tableModel = new DefaultTableModel();
        String[] cols = new String[]{"MÃ NV", "TÊN NV", "SDT", "VAI TRÒ", "EMAIL", "ĐỊA CHỈ", "GIỚI TÍNH", "TRẠNG THÁI", "NGÀY SINH"};
        tableModel.setColumnIdentifiers(cols);
        tblQLNV.setModel(tableModel);
    }
    
    public void fillTable() {
        tableModel.setRowCount(0);
        for (NhanVien nv : nvDAO.getAllNV12()) {
            tableModel.addRow(nvDAO.getRow(nv));
        }
    }
    
    
    TkhoanDAO tkDao = new TkhoanDAO(); // Khai báo ở đầu class
private void chonNhanVien() {
    int selectedRow = tblQLNV.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên!");
        return;
    }

    String maNV = tblQLNV.getValueAt(selectedRow, 0).toString();
    String vtro = tblQLNV.getValueAt(selectedRow, 3).toString(); // Lấy vai trò từ cột 3

    // Kiểm tra mã nhân viên đã có tài khoản chưa
    if (tkDao.kiemTraTonTaiTaiKhoan(maNV)) {
        JOptionPane.showMessageDialog(this, "Nhân viên này đã có tài khoản!");
        return;
    }

    // Gửi cả mã NV và vai trò qua listener
    if (listener != null) {
        listener.onNhanVienSelected(maNV, vtro); // Thêm vtro vào đây
    }

    this.dispose();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLNV = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("Chọn");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblQLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblQLNV);

        jButton3.setText("Chọn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        chonNhanVien();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chonnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chonnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chonnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chonnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        Chonnhanvien dialog = new Chonnhanvien(
            new javax.swing.JFrame(), 
            true, 
            new NhanVienSelectionListener() {
                @Override
                public void onNhanVienSelected(String maNV, String vtro) {  // Thêm tham số vtro
                    System.out.println("Đã chọn mã: " + maNV);
                    System.out.println("Vai trò: " + vtro);  // Hiển thị thêm vai trò
                }
            }
        );
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQLNV;
    // End of variables declaration//GEN-END:variables
}
